### ISSUE TITLE
Java 9: '--version' is broken

### ISSUE THREAD

**Issue by stiankri** [schibsted/strongbox#27]
When using Java 9, getting the version is broken
```
$ strongbox --version
strongbox version 'null'
```
The current implementation extracts `Implementation-Version` from `META-INF/MANIFEST.MF`:
https://github.com/schibsted/strongbox/blob/311a03bf822da55fcd8c69fd2138b437038d69cf/cli/src/main/java/com/schibsted/security/strongbox/cli/view/Global.java#L80

This needs to be rewritten with something that is compatible with both Java 9 and Java 8.

**Comment by biochimia** [comment]
For the record, it seems the issue goes away again with Java 10.
