### ISSUE TITLE
Strongbox debian install failure

### ISSUE THREAD

**Issue by emilva** [schibsted/strongbox#68]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Strongbox-cli debian install package

##### OS / ENVIRONMENT

Ubuntu

##### SUMMARY
`apt-get install strongbox-cli` fails

##### STEPS TO REPRODUCE

Follow install instructions:
`wget -O /tmp/strongbox-release_1-1_all.deb https://github.com/schibsted/strongbox/raw/repos/strongbox-release_1-1_all.deb && dpkg -i /tmp/strongbox-release_1-1_all.deb`
`apt-get update && apt-get install strongbox-cli`

##### EXPECTED RESULTS

Successful installation

##### ACTUAL RESULTS

`W: Failed to fetch http://dl.bintray.com/strongbox/strongbox-deb/dists/debian/Release  Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)`

**Comment by emilva** [comment]
No idea why this problem suddenly started. Installation works if you add `[arch=amd64]` to `strongbox.list`: `deb [arch=amd64] http://dl.bintray.com/strongbox/strongbox-deb debian main` not sure if this is the proper way to fix this issue.

**Comment by stiankri** [comment]
We might have tested this on a system that did not default to `i386`. Explicitly stating `[arch=amd64]` matches what we have in the [upload script](https://github.com/schibsted/strongbox/blob/master/script/descriptor-deb.json.tmpl#L33), and seems like a reasonable fix.

**Comment by xen0l** [comment]
Yes, I can confirm this. We will need to roll out new repository package files for Debian.
